version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_NAME_PATTERN: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /var/lib/kafka/data

  dotnet-producer:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet-producer
    volumes:
      - ./dotnet-app:/app
    working_dir: /app
    command: dotnet run --project KafkaProducer

  dotnet-consumer:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: dotnet-consumer
    volumes:
      - ./dotnet-app:/app
    working_dir: /app
    command: dotnet run --project KafkaConsumer
